# Exercises to memorize important methods and general stuff

### Exercises to Understand `reshape` in 
'''
1.   Convert the following 1D array into a 2D array with 3 rows and 2 columns:  
   

2. **Flattening an Array**  
   Convert the following 2D array into a 1D array:  
   
3. **Using `-1` in Reshape**  
   Reshape the following array into 2 rows, letting  Python automatically calculate the number of columns:
   
4. **Incompatible Shapes**  
What happens when you try to reshape the following array into a shape (4, 2)?
   
'''

In [1]:
#Q1
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])

In [2]:
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
#Q2
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [ ]:
#Q3
arr = np.array([1, 2, 3, 4, 5, 6])

In [13]:
arr.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
#Q4
arr.reshape(4,2)

ValueError: cannot reshape array of size 6 into shape (4,2)

## .loc /.iloc

In [28]:
'''
Exercises to Understand loc vs. iloc in Pandas
Selecting Rows by Label with loc
Select the row where the index is "b":

'''
import pandas as pd
data = {'A': [10, 20, 30], 'B': [40, 50, 60]}
df = pd.DataFrame(data, index=['a', 'b', 'c'])
row_b = df.loc["b"]  # Fill in this line
print(row_b)


A    20
B    50
Name: b, dtype: int64


In [24]:
df

A   B
a  10  40
b  20  50
c  30  60

In [26]:

#Selecting Rows by Position with iloc
#Select the second row (index position 1):
df.iloc[1]

A    20
B    50
Name: b, dtype: int64

In [29]:
#Column Selection with loc and iloc
#Use loc to select column "A" and iloc to select the first column:

df.loc[:,"A"]
df.iloc[:,0]

a    10
b    20
c    30
Name: A, dtype: int64

In [34]:

#Slicing Rows with loc and iloc
#Select the rows for index labels "a" and "b" using loc, and the first two rows using iloc:
print(df.loc[['a','b'],:])
print("using iloc")
print(df.iloc[0:2,:])

    A   B
a  10  40
b  20  50
using iloc
    A   B
a  10  40
b  20  50


In [39]:

#Boolean Indexing with loc
#Use loc to select rows where column "A" is greater than 15:

df.loc[df["A"] > 15]

A   B
b  20  50
c  30  60

In [40]:

#Common Pitfalls
#Predict the output of the following code and explain why:

print(df.loc[1])  # Try it!
print(df.iloc["b"])  # Try it!

KeyError: 1