In [1]:
import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors

In [2]:
df = pd.read_csv("treated_dataset.csv")

In [4]:
df

title  254  507  882  1424  \
0                                                  1984  9.0  0.0  0.0   0.0   
1                                   1st to Die: A Novel  0.0  0.0  0.0   0.0   
2                                     2010: Odyssey Two  0.0  0.0  0.0   0.0   
3                                     204 Rosewood Lane  0.0  0.0  0.0   0.0   
4                                              24 Hours  0.0  0.0  0.0   0.0   
...                                                 ...  ...  ...  ...   ...   
1032                                    Year of Wonders  0.0  0.0  0.0   7.0   
1033                                   You Belong To Me  0.0  0.0  0.0   0.0   
1034  Zen and the Art of Motorcycle Maintenance: An ...  0.0  0.0  0.0   0.0   
1035                                               Zoya  0.0  0.0  0.0   0.0   
1036                                \O\" Is for Outlaw"  0.0  0.0  0.0   0.0   

      1435  1733  1903  2033  2110  ...  275020  275970  276463  276680  \
0      0.0   0.0   0.0   0.0   0.0  ...     0.0     0.0     0.0     0.0   
1      0.0   0.0   0.0   0.0   0.0  ...     0.0     0.0     0.0     0.0   
2      0.0   0.0   0.0   0.0   0.0  ...     0.0     0.0     0.0     0.0   
3      0.0   0.0   0.0   0.0   0.0  ...     0.0     0.0     0.0     0.0   
4      0.0   0.0   0.0   0.0   0.0  ...     0.0     0.0     0.0     0.0   
...    ...   ...   ...   ...   ...  ...     ...     ...     ...     ...   
1032   0.0   0.0   0.0   0.0   0.0  ...     0.0     0.0     0.0     0.0   
1033   0.0   0.0   0.0   0.0   0.0  ...     0.0     0.0     0.0     0.0   
1034   0.0   0.0   0.0   0.0   0.0  ...     0.0     0.0     0.0     0.0   
1035   0.0   0.0   0.0   0.0   0.0  ...     0.0     0.0     0.0     0.0   
1036   0.0   0.0   0.0   0.0   0.0  ...     0.0     0.0     0.0     0.0   

      277427  277478  277639  278137  278188  278418  
0        0.0     0.0     0.0     0.0     0.0     0.0  
1        0.0     0.0     0.0     0.0     0.0     0.0  
2        0.0     0.0     0.0     0.0     0.0     0.0  
3        0.0     0.0     0.0     0.0     0.0     0.0  
4       10.0     0.0     0.0     0.0     0.0     0.0  
...      ...     ...     ...     ...     ...     ...  
1032     0.0     0.0     0.0     0.0     0.0     0.0  
1033     0.0     0.0     0.0     0.0     0.0     0.0  
1034     0.0     0.0     0.0     0.0     0.0     0.0  
1035     0.0     0.0     0.0     0.0     0.0     0.0  
1036     0.0     0.0     0.0     0.0     0.0     0.0  

[1037 rows x 1629 columns]

In [5]:
input_matrix = csr_matrix(df.drop('title',axis=1))

In [6]:
input_matrix

<1037x1628 sparse matrix of type '<class 'numpy.float64'>'
	with 25570 stored elements in Compressed Sparse Row format>

In [7]:
nn = NearestNeighbors(algorithm="brute")
nn.fit(input_matrix)

NearestNeighbors(algorithm='brute')

In [19]:
nn.kneighbors(df.iloc[1032,1:].values.reshape(1,-1),n_neighbors=6)

(array([[ 0.        , 49.76946855, 51.04899607, 51.70106382, 51.79768335,
         51.82663408]]),
 array([[1032, 1007,  964,  501,  317,  950]], dtype=int64))

array([[0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object)